### ISSUE TITLE
Set up ESLint

### ISSUE THREAD

**Issue by const8ine** [open-genes/open-genes-frontend#15]
- [x] Install [Angular ESLint](https://github.com/angular-eslint/angular-eslint)
- [x] Configure ESLint accordingly to Angular style guide
- [x] Setup Prettier ([article on Medium](https://dev.to/bzvyagintsev/migrate-angular-app-to-eslint-with-prettier-airbnb-styleguide-husky-and-lint-staged-862))
- [x] Fix all occurrences in code with linter

**Comment by bhanu7755** [comment]
Can you assign this to me?

**Comment by const8ine** [comment]
Sure, assigned it to you

**Comment by bhanu7755** [comment]
Fixed all code occurrences as well
