### ISSUE TITLE
Links under gene ontology section are invalid, missing prefix GO:

### ISSUE THREAD

**Issue by kptoemail** [open-genes/open-genes-frontend#303]
The links attached to the elements (shown in the screenshot) are not correct. For example the circled button links to `https://www.ebi.ac.uk/QuickGO/term/0006897` which is incorrect. It should be `https://www.ebi.ac.uk/QuickGO/term/GO:0006897`. Mind the `GO:` prefix.

The API is returning the GOId correctly so this is a front end issue.
![bug](https://github.com/open-genes/open-genes-frontend/assets/131465817/cab591d1-3442-4744-9fac-cde8824f6ebe)

**Comment by const8ine** [comment]
Hello! Thank you for using Open Genes and for submitting your bug report! We've already fixed this issue in #300, however it wasn't yet in the production. I've now made a deployment of a new version with this issue fixed. Please check it out
