### ISSUE TITLE
Работа по данным проекта?

### ISSUE THREAD

**Issue by prozion** [open-genes/open-genes-frontend#36]
Извините, что не в тему. Но не нашел другого места куда написать.
Есть ли возможности как-то взаимодействовать с проектом open-genes в части работы с данными по генам? А то в РТД чате ставят в упрек, что мы пилим что-то свое и не думаем о помощи проектам Open Longevity.
Действительно, надо, как минимум, спросить. Проект ведь у вас замечательный. Может как-то реально помочь, в меру сил и компетенций?

**Comment by const8ine** [comment]
Здравуствуйте! Я обязательно сделаю специальное обсуждения в проекте для вопросов. Как бы вы хотели помогать по работе с данными? Мы еще выстраиваем взаимодействие с волонтерами по этой части. Сейчас у нас есть отдельные задачи на бэкенд по БД, задачи по добавлению данных из других баз, парсингу, которые мы скоро тоже перенесем на GitHub. И еще есть биологи, которые вносят часть данных вручную, анализируя научные публикации.

**Comment by const8ine** [comment]
Здравствуйте! Я обязательно сделаю специальное обсуждения в проекте для вопросов. Как бы вы хотели помогать по работе с данными? Мы еще выстраиваем взаимодействие с волонтерами по этой части. Сейчас у нас есть отдельные задачи на бэкенд по БД, задачи по добавлению данных из других баз, парсингу, которые мы скоро тоже перенесем на GitHub. И еще есть биологи, которые вносят часть данных вручную, анализируя научные публикации.
