### ISSUE TITLE
Develop a service to detect the user's language

### ISSUE THREAD

**Issue by const8ine** [open-genes/open-genes-frontend#5]
Develop a service to detect the user's language and set the corresponding language

- Develop a service that interacts with TranslateService to set the user's language. Now we have only two languages (English, Russian). 
- Use Russian if the user's language corresponds to Russian or one of the CIS languages: Ukrainian, Belarussian, Uzbek, Armenian and etc [full list](https://en.wikipedia.org/wiki/Commonwealth_of_Independent_States).
- Use English in any other cases. We will add more languages in the future, but now we are able to support only these both.

**Comment by thedevankit** [comment]
Can we detect browser language and on the basis of that can we set the language. ?

**Comment by const8ine** [comment]
Yes, sure

**Comment by const8ine** [comment]
May I assign this task to you?

**Comment by thedevankit** [comment]
Yes

**Comment by const8ine** [comment]
Please turn your attention to this part:
> - Use Russian if the user's language corresponds to Russian or one of the CIS languages: Ukrainian, Belarussian, Uzbek, Armenian and etc full list.
> - Use English in any other cases. We will add more languages in the future, but now we are able to support only these both.
